---
title: Nextra Blog
timezone: UTC
collections:
  pages-posts:
    title: Posts
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
prose:
  media: public/images
